// @generated by drawing-tools-generator. DO NOT EDIT.

# {{TOOL_ID}} Drawing Tool

- Feature Flag: `{{FEATURE_FLAG}}`
- Spec Source: `{{SPEC_PATH_NO_EXT}}.(json|yaml)`

## Anchors
{{ANCHOR_LIST}}

## Handles
{{HANDLE_LIST}}

## States
{{STATE_LIST}}

## Options
{{OPTION_LIST}}