// @generated by drawing-tools-generator. DO NOT EDIT.

import type { DrawingEnvironment, DrawingPointerEvent } from '../../types';

export function {{RUNTIME_CONTEXT_FUNC}}(_environment: DrawingEnvironment): void {
	// TODO({{TOOL_ID}}): implement runtime helpers for {{TOOL_ID}} tool
}

export function {{POINTER_HELPER_FUNC}}(_event: DrawingPointerEvent): void {
	// TODO({{TOOL_ID}}): implement pointer helper
}