// @generated by drawing-tools-generator. DO NOT EDIT.

import type { DrawingEnvironment, DrawingPointerEvent } from '../../types';

// Lightweight Charts Drawing Tool runtime helpers for {{TOOL_ID}}
// See docs/internal/drawing-primitives-architecture.md for architecture notes.

export function {{RUNTIME_CONTEXT_FUNC}}(_environment: DrawingEnvironment): void {
	// runtime stubs intentionally minimal; tool implementations own logic
}

export function {{POINTER_HELPER_FUNC}}(_event: DrawingPointerEvent): void {
	// pointer helper stub; integrate within tool as needed
}
