 // @generated by drawing-tools-generator. DO NOT EDIT.

import { describe, it } from 'node:test';
import { expect } from 'chai';
import { {{SPEC_CONST}} } from '../../../../src/drawing/tools/__generated__/{{TOOL_FILE_NAME}}';

describe('{{TOOL_ID}} drawing tool (generated)', () => {
	it('exposes metadata from the spec', () => {
		expect({{SPEC_CONST}}.toolId).to.equal('{{TOOL_ID}}');
		expect({{SPEC_CONST}}.featureFlag).to.equal('{{FEATURE_FLAG}}');
	});

	it('includes anchors and states', () => {
		expect(Array.isArray({{SPEC_CONST}}.anchors)).to.equal(true);
		expect(Array.isArray({{SPEC_CONST}}.states)).to.equal(true);
	});
});