 // @generated by drawing-tools-generator. DO NOT EDIT.

import { describe, it } from 'node:test';
import { expect } from 'chai';
import { priceLineShadowSpec } from '../../../../src/drawing/tools/__generated__/price-line-shadow';

describe('price-line-shadow drawing tool (generated)', () => {
	it('exposes metadata from the spec', () => {
		expect(priceLineShadowSpec.toolId).to.equal('price-line-shadow');
		expect(priceLineShadowSpec.featureFlag).to.equal('drawingTools.priceLineShadow');
	});

	it('includes anchors and states', () => {
		expect(Array.isArray(priceLineShadowSpec.anchors)).to.equal(true);
		expect(Array.isArray(priceLineShadowSpec.states)).to.equal(true);
	});
});
