 // @generated by drawing-tools-generator. DO NOT EDIT.

import { describe, it } from 'node:test';
import { expect } from 'chai';
import { rectangleSpec } from '../../../../src/drawing/tools/__generated__/rectangle';

describe('rectangle drawing tool (generated)', () => {
	it('exposes metadata from the spec', () => {
		expect(rectangleSpec.toolId).to.equal('rectangle');
		expect(rectangleSpec.featureFlag).to.equal('drawingTools.rectangle');
	});

	it('includes anchors and states', () => {
		expect(Array.isArray(rectangleSpec.anchors)).to.equal(true);
		expect(Array.isArray(rectangleSpec.states)).to.equal(true);
	});
});
