 // @generated by drawing-tools-generator. DO NOT EDIT.

import { describe, it } from 'node:test';
import { expect } from 'chai';
import { seriesMarkersShadowSpec } from '../../../../src/drawing/tools/__generated__/series-markers-shadow';

describe('series-markers-shadow drawing tool (generated)', () => {
	it('exposes metadata from the spec', () => {
		expect(seriesMarkersShadowSpec.toolId).to.equal('series-markers-shadow');
		expect(seriesMarkersShadowSpec.featureFlag).to.equal('drawingTools.seriesMarkersShadow');
	});

	it('includes anchors and states', () => {
		expect(Array.isArray(seriesMarkersShadowSpec.anchors)).to.equal(true);
		expect(Array.isArray(seriesMarkersShadowSpec.states)).to.equal(true);
	});
});
