 // @generated by drawing-tools-generator. DO NOT EDIT.

import { describe, it } from 'node:test';
import { expect } from 'chai';
import { watermarkTextShadowSpec } from '../../../../src/drawing/tools/__generated__/watermark-text-shadow';

describe('watermark-text-shadow drawing tool (generated)', () => {
	it('exposes metadata from the spec', () => {
		expect(watermarkTextShadowSpec.toolId).to.equal('watermark-text-shadow');
		expect(watermarkTextShadowSpec.featureFlag).to.equal('drawingTools.watermarkTextShadow');
	});

	it('includes anchors and states', () => {
		expect(Array.isArray(watermarkTextShadowSpec.anchors)).to.equal(true);
		expect(Array.isArray(watermarkTextShadowSpec.states)).to.equal(true);
	});
});
