 // @generated by drawing-tools-generator. DO NOT EDIT.

import { describe, it } from 'node:test';
import { expect } from 'chai';
import { watermarkImageShadowSpec } from '../../../../src/drawing/tools/__generated__/watermark-image-shadow';

describe('watermark-image-shadow drawing tool (generated)', () => {
	it('exposes metadata from the spec', () => {
		expect(watermarkImageShadowSpec.toolId).to.equal('watermark-image-shadow');
		expect(watermarkImageShadowSpec.featureFlag).to.equal('drawingTools.watermarkImageShadow');
	});

	it('includes anchors and states', () => {
		expect(Array.isArray(watermarkImageShadowSpec.anchors)).to.equal(true);
		expect(Array.isArray(watermarkImageShadowSpec.states)).to.equal(true);
	});
});
