// @generated by drawing-tools-generator. DO NOT EDIT.

import type { DrawingEnvironment, DrawingPointerEvent } from '../../types';

export function createPriceLineShadowRuntimeContext(_environment: DrawingEnvironment): void {
	// TODO(price-line-shadow): implement runtime helpers for price-line-shadow tool
}

export function priceLineShadowHandlePointer(_event: DrawingPointerEvent): void {
	// TODO(price-line-shadow): implement pointer helper
}
