// @generated by drawing-tools-generator. DO NOT EDIT.

import type { DrawingEnvironment, DrawingPointerEvent } from '../../types';

export function createRectangleRuntimeContext(_environment: DrawingEnvironment): void {
	// TODO(rectangle): implement runtime helpers for rectangle tool
}

export function rectangleHandlePointer(_event: DrawingPointerEvent): void {
	// TODO(rectangle): implement pointer helper
}
