// @generated by drawing-tools-generator. DO NOT EDIT.

import type { DrawingEnvironment, DrawingPointerEvent } from '../../types';

export function createSeriesMarkersShadowRuntimeContext(_environment: DrawingEnvironment): void {
	// TODO(series-markers-shadow): implement runtime helpers for series-markers-shadow tool
}

export function seriesMarkersShadowHandlePointer(_event: DrawingPointerEvent): void {
	// TODO(series-markers-shadow): implement pointer helper
}
