// @generated by drawing-tools-generator. DO NOT EDIT.

import type { DrawingEnvironment, DrawingPointerEvent } from '../../types';

export function createWatermarkImageShadowRuntimeContext(_environment: DrawingEnvironment): void {
	// TODO(watermark-image-shadow): implement runtime helpers for watermark-image-shadow tool
}

export function watermarkImageShadowHandlePointer(_event: DrawingPointerEvent): void {
	// TODO(watermark-image-shadow): implement pointer helper
}
