// @generated by drawing-tools-generator. DO NOT EDIT.

import type { DrawingEnvironment, DrawingPointerEvent } from '../../types';

export function createWatermarkTextShadowRuntimeContext(_environment: DrawingEnvironment): void {
	// TODO(watermark-text-shadow): implement runtime helpers for watermark-text-shadow tool
}

export function watermarkTextShadowHandlePointer(_event: DrawingPointerEvent): void {
	// TODO(watermark-text-shadow): implement pointer helper
}
