// @generated by drawing-tools-generator. DO NOT EDIT.

import type { DrawingEnvironment, DrawingPointerEvent } from '../../types';

// Lightweight Charts Drawing Tool runtime helpers for watermark-image-shadow
// See docs/internal/drawing-primitives-architecture.md for architecture notes.

export function createWatermarkImageShadowRuntimeContext(_environment: DrawingEnvironment): void {
	// runtime stubs intentionally minimal; tool implementations own logic
}

export function watermarkImageShadowHandlePointer(_event: DrawingPointerEvent): void {
	// pointer helper stub; integrate within tool as needed
}
